### ISSUE TITLE
Horizontal striping in earth_relief_30s?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/remote-datasets#32]
There are horizontal lines in offshore area. I think it is an error in the processing.
![Earth_30s](https://user-images.githubusercontent.com/17908951/157871923-f0e25b88-8cc8-40b5-b14f-712bfb6eca86.png)

This is 15s without those lines.
![Earth_15s](https://user-images.githubusercontent.com/17908951/157872057-3b0d221a-d644-45a3-a116-64c41c1590bc.png)

```
gmt grdimage @earth_relief_30s -png Earth_30s -I -RFK+r1 -Baf
gmt grdimage @earth_relief_15s -png Earth_15s -I -RFK+r1 -Baf
```

**Comment by meghanrjones** [comment]
@PaulWessel, do you think this is worthwhile to look at before remaking the `earth_relief` files?

**Comment by PaulWessel** [comment]
Yes, we should do that.  I suspect the filter width is just a tad too small so that alternate rows ends up with uneven results.
Maybe a simple test would be to take a grdcut of the 15s exampe above and just do the grdfilter step that the recipe would call for (i.e., first reproduce the same plot but manuallyl via grdfilter) then increase the filtering a bit. This is what we have

FILTER_WIDTH=$(gmt math -Q ${SRC_RADIUS} 2 MUL PI MUL 360 DIV $INC MUL 0.05 ADD 10 MUL RINT 10 DIV =)

Perhaps the 0.05 is too small - try 0.1.  For 30s the above yields 

1.  Perhaps first try to replace RINT with CEIL and use 0.1.  Then we get 1.1 instead of 1.

**Comment by PaulWessel** [comment]
@Esteban82, I take it there are no problems in the 01m and coarser grids?  if so then I think it will go away with another padding than 0.05 and with CEIL rather than RINT.

**Comment by Esteban82** [comment]
> @Esteban82, I take it there are no problems in the 01m and coarser grids?

Exactly. I only find the problem with that 30s resolution.

**Comment by PaulWessel** [comment]
First check on filtering the original grid to 30s with the same parameters as the script we us gave no stripes.  So now running the full job to see if it gives stripes (the files on the server has stripes obviously) since it all looks good on paper. FYI, the 30s grid is filtered with a 5x5 node filter which should be perfect for 15s going to 30s and it looked fine when I do it manually...

**Comment by PaulWessel** [comment]
Maybe something to do with our rounding to nearest 0.5 meter and/or compression - we will find out.

**Comment by PaulWessel** [comment]
I can confirm the srv_downsampler_grid.sh does create those stripes; not clear why yet.

**Comment by PaulWessel** [comment]
I cannot find a specific problem, but likely to be related to int64 counting.  I was able to do a work-around: Filter the N and S hemispheres separately, **grdpaste** them, then run **grdedit** to set the remark and then **grdconvert** to shrink to 50cm ints:

```
gmt grdfilter SRTM15_V2.4.nc -Fg1 -D1 -I30s -rp -Gnew_30s_p_n.grd--PROJ_ELLIPSOID=Sphere -R-180/180/0/90
gmt grdfilter SRTM15_V2.4.nc -Fg1 -D1 -I30s -rp -Gnew_30s_p_n.grd --PROJ_ELLIPSOID=Sphere -R-180/180/0/90
gmt grdpaste new_30s_p_n.grd new_30s_p_s.grd -Gboth.grd -V
gmt grdedit both.grd -D+r"Reduced by Gaussian Cartesian filtering (1 km fullwidth) from SRTM15_V2.4.nc [Sandwell et al., 2022; https://doi.org/10.1029/2021EA002069]"
gmt grdconvert both.grd -Gearth_relief_30s_p.grd=ns+s0.5+o0 --IO_NC4_DEFLATION_LEVEL=9 --IO_NC4_CHUNK_SIZE=4096
```

The result does not have any of those stripes when you run

`gmt grdimage  -R62W/57W/53S/51S earth_relief_30s_p.grd -Cgeo -B -I -png new
`

@meghanrjones, I think it is best to do this for all the 30s products derived from a 15s product, so probably gebco, gebco_si as well as the Scripps files.

**Comment by meghanrjones** [comment]
Is this something that should be included in the recipes for those datasets?

**Comment by PaulWessel** [comment]
Hm, well I had hoped to find and fix the bug but it has proven elusive.  Perhaps I should add this special trick to the srv_downsampler_grid script.  I can do that since we may be doing this for a while if we cannot find the problem,

**Comment by PaulWessel** [comment]
I have opened a PR for you @meghanrjones.  I think I got the region and pieces correctly (the steps above had cut/paste issues).

**Comment by meghanrjones** [comment]
> I have opened a PR for you @meghanrjones. I think I got the region and pieces correctly (the steps above had cut/paste issues).

Thanks. I try out remaking the datasets tomorrow.

**Comment by PaulWessel** [comment]
Just leaving a note here that the recent fix in GMT regarding macOS vDSP use for scaling large output grids does not affect this - it is clearly a **grdfilter** issue.

**Comment by PaulWessel** [comment]
Hi @Esteban82, perhaps you can have a look at this and maybe zoom into other areas to see if I am right. Below are two bathymetry plots with no shading, using the area `-R57:40W/57W/48:10S/47:50S` with the SRTM15 file and then the 30s global filtered file (with the stripes above);

### 15s original:
![Earth_15sx](https://user-images.githubusercontent.com/26473567/212549979-05c66e33-9894-4bbc-8e7f-8c3c55ca2087.png)

### 30s filtered:
![Earth_30sx](https://user-images.githubusercontent.com/26473567/212549993-1114e531-3903-45d2-82ea-2e72ff7d0ee4.png)

Now, we apply -I+d as default shading:

### 15s with shading:
![Earth_15sxi](https://user-images.githubusercontent.com/26473567/212550032-fc043af6-8def-4046-84db-dd042213db0c.png)

### 30s with shading:
![Earth_30sxi](https://user-images.githubusercontent.com/26473567/212550040-9bbfafcc-55b4-43a3-9cd2-16e83e6699e0.png)

To my eyes, the 15s -> 30s filtering looks reasonable: The pixels are twice as large and hence it looks a bit blockier but the transitions look reasonable and nothing odd stands out.  Once we do shading then the 15s looks OK while the 30s looks very striped.  This leads me to wonder if the problem lies with the **grdgradient** call that **grdimage** does in order to do the shading.  What do you think, @GenericMappingTools/core ?

**Comment by PaulWessel** [comment]
Maybe create some N-S cross-profiles of the 15s and 30s to see if there are any odd steps in 30s.

**Comment by Esteban82** [comment]
Yes, I was thinking on making profiles.

**Comment by Esteban82** [comment]
First I made these 2 figures. When I compare the 15s (_p by default) vs 30s_p the profiles (a NS black line in the middle of the map) loks very similar. 

![32_Mapa_Perfil_30s_p](https://user-images.githubusercontent.com/17908951/212692326-f4ef1856-2442-41ce-80bd-e4a1a5d0e15e.png)

![32_Mapa_Perfil_15s](https://user-images.githubusercontent.com/17908951/212692316-99f94d2d-c323-4045-a4ec-9d5fdc7a42ae.png)

However, I got this very strange map when I used 30s_g.

![32_Mapa_Perfil_30s_g](https://user-images.githubusercontent.com/17908951/212692323-43922823-a5a1-496b-a181-0cabee6c42f3.png)

**Comment by Esteban82** [comment]
![Earth_30s_g](https://user-images.githubusercontent.com/17908951/212695891-c5833edd-3864-499c-a27b-336bcd961e0f.png)
![Earth_30s_p](https://user-images.githubusercontent.com/17908951/212695897-7fdf19e2-b3e8-4882-a09f-b850fdbb7d24.png)

```
gmt grdimage @earth_relief_30s_g -png Earth_30s_g -I -R-57:40/-57/-48:10/-47:50 -Baf -B+t"Gridline"
gmt grdimage @earth_relief_30s_p -png Earth_30s_p -I -R-57:40/-57/-48:10/-47:50 -Baf -B+t"Pixel"
```

**Comment by Esteban82** [comment]
This is GEBCO


![Gebco_30s_g](https://user-images.githubusercontent.com/17908951/212696294-839666cc-88c7-4559-a67f-ec77a8696fed.png)

**Comment by Esteban82** [comment]
I reopened by mistake.

**Comment by WalterHFSmith** [comment]
Hi,

I am glad you were able to close the issue, but I didn’t understand what the resolution was.

Did someone mistakenly compare the GEBCO product to a product from the SRTM15Plus or SYNBATH of Sandwell et al?

Or was the pointer to the 30s grid selecting the wrong grid?

Is there an issue with the way the filtering/downsampling is done at high latitude that makes gradients look strange in cylindrical projections?

Thanks,

W

**Comment by PaulWessel** [comment]
`gmt grdimage @earth_relief_30s_g -png Earth_30s -I -RFK+r1 -Baf`

gives pretty much the same plot at the top of this thread, so that part seems OK.

**Comment by Esteban82** [comment]
OK, so I don't know what is my problem. I remove the grids and I got a wrong figure. I use oceania server. What server should I use?
