### ISSUE TITLE
Automate building of the *.rst snippets

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/remote-datasets#82]
Right now, pieces like `earth-faa.rst `are manually maintained.  However, with soon > 20 datasets this gets tedious.  I suggest we instead maintain either a single text file with the background on each data set (or, alternatively, one small txt file for each).  Then, a script can loop over these and make individual RST snippet like` earth-faa.rst`. In addition to the preamble given by the small txt files and the inclusion of files like _GMT_faa.jpg_), the script will need to 

- Format the Usage section
- Build the tables (e.g.,` _tbl-earth_faa`). The dimensions and etc is available on the candidate server, for instance, or locally.
- Any data references might be comments in the txt file that if > 0 records builds a Data References section

**Comment by seisman** [comment]
I tried the idea a few months ago in c71a22956e0f524ecd950a1145c8bbe0cc537dd9, and found that it's possible to have the script but the script is more likely difficult to maintain. Since we're not updating these pages frequently, I guess it's fine to manually maintain them.

So, I'm closing the issue, but feel free to reopen it if anyone is still interested in this idea.

**Comment by Esteban82** [comment]
> the script is more likely difficult to maintain

Why was that?

**Comment by seisman** [comment]
The unfinished script in c71a22956e0f524ecd950a1145c8bbe0cc537dd9 is long and contains many if-test statements, so it's not easy to read. I guess no one else will maintain the script if I get hit by a bus. So using plaintext files is much simpler.

**Comment by Esteban82** [comment]
Ok, I see. Thanks.
