### ISSUE TITLE
Homogenize maps in the website

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/remote-datasets#88]
There are some small differences in the static figures (https://www.generic-mapping-tools.org/remote-datasets/index.html).

The idea is to make all similar (and add scripts to those that don't have).

Important doubts:
1. Should I extend the maps at to the poles (for those that don't have data their)? I think we should so the users can clearly see the lack of the data there (and also all the figures have the same size).

Minor doubts:
1. With or without a frame? Some of them have. 
2. There are maps with jpg and png format. I should respect that, right?

**Comment by PaulWessel** [comment]
1. It may be cleaner to have the full -Rd view even if it stops at 82N and gets blocked by Antarctica in the south.
2. 2. I think no frame is good.  These images are just showing what it is, crudely.
3. Just happen because these were mostly one-off. If jpg is smaller then perhaps that makes more sense?

**Comment by PaulWessel** [comment]
All good.

**Comment by Esteban82** [comment]
Done by #91.
